### ISSUE TITLE
Multi Source in B1 and B2

### ISSUE THREAD

**Issue by stebubu** [gecosistema/SOILGIS#1]
Dare la possibilità di fare il run da multi sorgenti in un area di studio

Sviluppo:
if source_coc= coc

for each source:
  stima plume numpy
sum(numpy) if stesso COC

**Comment by valluzzi** [comment]
Sto incontrando le seguenti problematiche:
- L'applicazione della distance e aspect va effettuata su uno shape  che va semplificato o ricostruito con una sola feature per volta. (vedo io come fare) 
- Il grafico della centerline che attualmente visualizza l'andamento sulla centerline di una sorgente cosa dovrebbe visualizzare ora? (Ora ci sono due grafici della centerline. 1 nella maschera e uno generato come grafico di Arcmap)

**Comment by stebubu** [comment]
si genera solo il raster non stazionario con t e z fissi per tutte le sorgenti
facciamo 2 grafici di ArcMap - 1 tutte sorgenti stato stazionario e 1 tutte sorgenti con t fissato
nel grafico centerline sull'interfaccia si vedono gli andamenti staz e non staz per la sorgente selezionata

**Comment by valluzzi** [comment]
Facciamo un grafico per ogni sorgente:
-curva stazionaria
-curva transitorio
-csc
