### ISSUE TITLE
Aggiornare i riferimenti bibliografici dei modelli

### ISSUE THREAD

**Issue by valluzzi** [gecosistema/SOILGIS#26]
Bisognerebbe aggiornare i riferimenti bibliografici dei modelli nella maschera della selezione dello scenario

**Comment by stebubu** [comment]
van Genuchten, M. Th., and W. J. Alves. 1982. Analytical solutions of the one-dimensional convective-dispersive solute transport equation. Tech. Bulletin 1661. Washington, D.C.: USDA-ARS
