### ISSUE TITLE
Ultime Modifiche SOIL-GIS

### ISSUE THREAD

**Issue by stebubu** [gecosistema/SOILGIS#30]
1) Eliminare la legenda fissa in B1
2) Eliminare A2 e Rinominare A1 Continuos/Istantaneous
3) Spostare Ugw*t e Ugwz*t dove c'è il tempo (nella task successiva)
4) ti ricordi altro????

**Comment by valluzzi** [comment]
SOILGIS_UserManual_Tutorial_v4.4_rev7.2.docx
SoilGis4Saipem_v0.4.5.exe
sul drive

**Comment by stebubu** [comment]
ok

From:  valluzzi <notifications@github.com>
Reply-To:  gecosistema/SOILGIS
<reply+0063c881f381a7a506d5c48a9c773f59026e298dd378624492cf0000000110ea1e5a9
2a169ce035a521c@reply.github.com>
Date:  Wednesday 4 February 2015 18:52
To:  gecosistema/SOILGIS <SOILGIS@noreply.github.com>
Cc:  Stefano Bagli <stefano.bagli@gecosistema.it>
Subject:  Re: [SOILGIS] Ultime Modifiche SOIL-GIS (#30)


SOILGIS_UserManual_Tutorial_v4.4_rev7.2.docx
SoilGis4Saipem_v0.4.5.exe
sul drive

‹
Reply to this email directly or view it on GitHub
<https://github.com/gecosistema/SOILGIS/issues/30#issuecomment-72903320> .
